<?php

namespace ContainerAtg6xlf;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5HTWn77Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5HTWn77' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5HTWn77'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'repo' => ['privates', 'App\\Repository\\BlogPostRepository', 'getBlogPostRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', true],
        ], [
            'repo' => 'App\\Repository\\BlogPostRepository',
            'serializer' => '?',
        ]);
    }
}
