<?php

namespace ContainerAtg6xlf;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OM8acy8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oM8acy8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oM8acy8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'blog' => ['privates', '.errored..service_locator.oM8acy8.App\\Entity\\BlogPost', NULL, 'Cannot autowire service ".service_locator.oM8acy8": it needs an instance of "App\\Entity\\BlogPost" but this type has been excluded in "config/services.yaml".'],
            'serializer' => ['privates', 'serializer', 'getSerializerService', true],
        ], [
            'blog' => 'App\\Entity\\BlogPost',
            'serializer' => '?',
        ]);
    }
}
