<?php

namespace ContainerOPsuqgI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MghMWYBService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.MghMWYB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MghMWYB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'accessTokenHandler' => ['privates', 'App\\Security\\AccessTokenHandler', 'getAccessTokenHandlerService', true],
            'authenticationUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'accessTokenHandler' => 'App\\Security\\AccessTokenHandler',
            'authenticationUtils' => '?',
            'security' => '?',
        ]);
    }
}
