<?php

namespace ContainerOPsuqgI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IJLaoRYService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.iJLaoRY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.iJLaoRY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'logger' => ['privates', 'logger', 'getLoggerService', false],
            'repo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'validator' => ['privates', 'validator', 'getValidatorService', true],
        ], [
            'logger' => '?',
            'repo' => 'App\\Repository\\UserRepository',
            'slugger' => '?',
            'validator' => '?',
        ]);
    }
}
