<?php

namespace ContainerOPsuqgI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1MKZjV2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.1MKZjV2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1MKZjV2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'blog' => ['privates', '.errored..service_locator.1MKZjV2.App\\Entity\\BlogPost', NULL, 'Cannot autowire service ".service_locator.1MKZjV2": it needs an instance of "App\\Entity\\BlogPost" but this type has been excluded in "config/services.yaml".'],
            'repo' => ['privates', 'App\\Repository\\CommentRepository', 'getCommentRepositoryService', true],
            'serializer' => ['privates', 'serializer', 'getSerializerService', true],
            'validator' => ['privates', 'validator', 'getValidatorService', true],
        ], [
            'blog' => 'App\\Entity\\BlogPost',
            'repo' => 'App\\Repository\\CommentRepository',
            'serializer' => '?',
            'validator' => '?',
        ]);
    }
}
