<?php

namespace ContainerOPsuqgI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getArgumentResolver_ServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'argument_resolver.service' shared service.
     *
     * @return \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\BlogPostController::addBlog' => ['privates', '.service_locator.r682ukv', 'get_ServiceLocator_R682ukvService', true],
            'App\\Controller\\BlogPostController::addComment' => ['privates', '.service_locator.1MKZjV2', 'get_ServiceLocator_1MKZjV2Service', true],
            'App\\Controller\\BlogPostController::editBlog' => ['privates', '.service_locator.xcCKT4K', 'get_ServiceLocator_XcCKT4KService', true],
            'App\\Controller\\BlogPostController::followPosts' => ['privates', '.service_locator.5HTWn77', 'get_ServiceLocator_5HTWn77Service', true],
            'App\\Controller\\BlogPostController::index' => ['privates', '.service_locator.5HTWn77', 'get_ServiceLocator_5HTWn77Service', true],
            'App\\Controller\\BlogPostController::showOne' => ['privates', '.service_locator.oM8acy8', 'get_ServiceLocator_OM8acy8Service', true],
            'App\\Controller\\BlogPostController::topLiked' => ['privates', '.service_locator.5HTWn77', 'get_ServiceLocator_5HTWn77Service', true],
            'App\\Controller\\FollowersController::follow' => ['privates', '.service_locator.y.pi5vY', 'get_ServiceLocator_Y_Pi5vYService', true],
            'App\\Controller\\FollowersController::unFollow' => ['privates', '.service_locator.y.pi5vY', 'get_ServiceLocator_Y_Pi5vYService', true],
            'App\\Controller\\LikeController::like' => ['privates', '.service_locator.FY3VIxc', 'get_ServiceLocator_FY3VIxcService', true],
            'App\\Controller\\LikeController::unlike' => ['privates', '.service_locator.FY3VIxc', 'get_ServiceLocator_FY3VIxcService', true],
            'App\\Controller\\LoginController::login' => ['privates', '.service_locator.MghMWYB', 'get_ServiceLocator_MghMWYBService', true],
            'App\\Controller\\ProfileController::followers' => ['privates', '.service_locator.G3Mz0uW', 'get_ServiceLocator_G3Mz0uWService', true],
            'App\\Controller\\ProfileController::following' => ['privates', '.service_locator.G3Mz0uW', 'get_ServiceLocator_G3Mz0uWService', true],
            'App\\Controller\\ProfileController::show' => ['privates', '.service_locator.WL4y3YD', 'get_ServiceLocator_WL4y3YDService', true],
            'App\\Controller\\ProfileSettingController::profile' => ['privates', '.service_locator.f_aBlYD', 'get_ServiceLocator_FABlYDService', true],
            'App\\Controller\\ProfileSettingController::profileImage' => ['privates', '.service_locator.iJLaoRY', 'get_ServiceLocator_IJLaoRYService', true],
            'App\\Controller\\RegistrationController::confirmEmail' => ['privates', '.service_locator.Jr0jWB9', 'get_ServiceLocator_Jr0jWB9Service', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.hEUWOlY', 'get_ServiceLocator_HEUWOlYService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\BlogPostController:addBlog' => ['privates', '.service_locator.r682ukv', 'get_ServiceLocator_R682ukvService', true],
            'App\\Controller\\BlogPostController:addComment' => ['privates', '.service_locator.1MKZjV2', 'get_ServiceLocator_1MKZjV2Service', true],
            'App\\Controller\\BlogPostController:editBlog' => ['privates', '.service_locator.xcCKT4K', 'get_ServiceLocator_XcCKT4KService', true],
            'App\\Controller\\BlogPostController:followPosts' => ['privates', '.service_locator.5HTWn77', 'get_ServiceLocator_5HTWn77Service', true],
            'App\\Controller\\BlogPostController:index' => ['privates', '.service_locator.5HTWn77', 'get_ServiceLocator_5HTWn77Service', true],
            'App\\Controller\\BlogPostController:showOne' => ['privates', '.service_locator.oM8acy8', 'get_ServiceLocator_OM8acy8Service', true],
            'App\\Controller\\BlogPostController:topLiked' => ['privates', '.service_locator.5HTWn77', 'get_ServiceLocator_5HTWn77Service', true],
            'App\\Controller\\FollowersController:follow' => ['privates', '.service_locator.y.pi5vY', 'get_ServiceLocator_Y_Pi5vYService', true],
            'App\\Controller\\FollowersController:unFollow' => ['privates', '.service_locator.y.pi5vY', 'get_ServiceLocator_Y_Pi5vYService', true],
            'App\\Controller\\LikeController:like' => ['privates', '.service_locator.FY3VIxc', 'get_ServiceLocator_FY3VIxcService', true],
            'App\\Controller\\LikeController:unlike' => ['privates', '.service_locator.FY3VIxc', 'get_ServiceLocator_FY3VIxcService', true],
            'App\\Controller\\LoginController:login' => ['privates', '.service_locator.MghMWYB', 'get_ServiceLocator_MghMWYBService', true],
            'App\\Controller\\ProfileController:followers' => ['privates', '.service_locator.G3Mz0uW', 'get_ServiceLocator_G3Mz0uWService', true],
            'App\\Controller\\ProfileController:following' => ['privates', '.service_locator.G3Mz0uW', 'get_ServiceLocator_G3Mz0uWService', true],
            'App\\Controller\\ProfileController:show' => ['privates', '.service_locator.WL4y3YD', 'get_ServiceLocator_WL4y3YDService', true],
            'App\\Controller\\ProfileSettingController:profile' => ['privates', '.service_locator.f_aBlYD', 'get_ServiceLocator_FABlYDService', true],
            'App\\Controller\\ProfileSettingController:profileImage' => ['privates', '.service_locator.iJLaoRY', 'get_ServiceLocator_IJLaoRYService', true],
            'App\\Controller\\RegistrationController:confirmEmail' => ['privates', '.service_locator.Jr0jWB9', 'get_ServiceLocator_Jr0jWB9Service', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.hEUWOlY', 'get_ServiceLocator_HEUWOlYService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\BlogPostController::addBlog' => '?',
            'App\\Controller\\BlogPostController::addComment' => '?',
            'App\\Controller\\BlogPostController::editBlog' => '?',
            'App\\Controller\\BlogPostController::followPosts' => '?',
            'App\\Controller\\BlogPostController::index' => '?',
            'App\\Controller\\BlogPostController::showOne' => '?',
            'App\\Controller\\BlogPostController::topLiked' => '?',
            'App\\Controller\\FollowersController::follow' => '?',
            'App\\Controller\\FollowersController::unFollow' => '?',
            'App\\Controller\\LikeController::like' => '?',
            'App\\Controller\\LikeController::unlike' => '?',
            'App\\Controller\\LoginController::login' => '?',
            'App\\Controller\\ProfileController::followers' => '?',
            'App\\Controller\\ProfileController::following' => '?',
            'App\\Controller\\ProfileController::show' => '?',
            'App\\Controller\\ProfileSettingController::profile' => '?',
            'App\\Controller\\ProfileSettingController::profileImage' => '?',
            'App\\Controller\\RegistrationController::confirmEmail' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\BlogPostController:addBlog' => '?',
            'App\\Controller\\BlogPostController:addComment' => '?',
            'App\\Controller\\BlogPostController:editBlog' => '?',
            'App\\Controller\\BlogPostController:followPosts' => '?',
            'App\\Controller\\BlogPostController:index' => '?',
            'App\\Controller\\BlogPostController:showOne' => '?',
            'App\\Controller\\BlogPostController:topLiked' => '?',
            'App\\Controller\\FollowersController:follow' => '?',
            'App\\Controller\\FollowersController:unFollow' => '?',
            'App\\Controller\\LikeController:like' => '?',
            'App\\Controller\\LikeController:unlike' => '?',
            'App\\Controller\\LoginController:login' => '?',
            'App\\Controller\\ProfileController:followers' => '?',
            'App\\Controller\\ProfileController:following' => '?',
            'App\\Controller\\ProfileController:show' => '?',
            'App\\Controller\\ProfileSettingController:profile' => '?',
            'App\\Controller\\ProfileSettingController:profileImage' => '?',
            'App\\Controller\\RegistrationController:confirmEmail' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]));
    }
}
