<?php

namespace ContainerOPsuqgI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAccessTokenHandlerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\AccessTokenHandler' shared autowired service.
     *
     * @return \App\Security\AccessTokenHandler
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = new \Redis();
        $a->connect($container->getEnv('key:host:url:REDIS_URL'), $container->getEnv('key:port:url:REDIS_URL'));
        $a->auth($container->getEnv('REDIS_PASSWORD'));

        return $container->privates['App\\Security\\AccessTokenHandler'] = new \App\Security\AccessTokenHandler($a);
    }
}
