<?php

namespace ContainerOPsuqgI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogPostVoterService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Security\Voter\BlogPostVoter' shared autowired service.
     *
     * @return \App\Security\Voter\BlogPostVoter
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService'));

        if (isset($container->privates['App\\Security\\Voter\\BlogPostVoter'])) {
            return $container->privates['App\\Security\\Voter\\BlogPostVoter'];
        }

        return $container->privates['App\\Security\\Voter\\BlogPostVoter'] = new \App\Security\Voter\BlogPostVoter($a);
    }
}
