<?php

namespace ContainerOPsuqgI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBlogPostControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\BlogPostController' shared autowired service.
     *
     * @return \App\Controller\BlogPostController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\BlogPostController'] = $instance = new \App\Controller\BlogPostController(($container->privates['logger'] ?? $container->getLoggerService()));

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\BlogPostController', $container));

        return $instance;
    }
}
