<?php

namespace ContainerOPsuqgI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFollowersControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\FollowersController' shared autowired service.
     *
     * @return \App\Controller\FollowersController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\FollowersController'] = $instance = new \App\Controller\FollowersController();

        $instance->setContainer(($container->privates['.service_locator.CshazM0'] ?? $container->load('get_ServiceLocator_CshazM0Service'))->withContext('App\\Controller\\FollowersController', $container));

        return $instance;
    }
}
