<?php

namespace ContainerOPsuqgI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Authenticator_AccessToken_MainService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.authenticator.access_token.main' shared service.
     *
     * @return \Symfony\Component\Security\Http\Authenticator\AccessTokenAuthenticator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['security.authenticator.access_token.main'] = new \Symfony\Component\Security\Http\Authenticator\AccessTokenAuthenticator(($container->privates['App\\Security\\AccessTokenHandler'] ?? $container->load('getAccessTokenHandlerService')), new \Symfony\Component\Security\Http\AccessToken\HeaderAccessTokenExtractor(), ($container->privates['security.user.provider.concrete.app_user_provider'] ?? $container->load('getSecurity_User_Provider_Concrete_AppUserProviderService')), NULL, NULL, NULL);
    }
}
