<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOPsuqgI\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOPsuqgI/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerOPsuqgI.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerOPsuqgI\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerOPsuqgI\App_KernelProdContainer([
    'container.build_hash' => 'OPsuqgI',
    'container.build_id' => 'c79c6bc3',
    'container.build_time' => 1704088536,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOPsuqgI');
