<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAtg6xlf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAtg6xlf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAtg6xlf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAtg6xlf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAtg6xlf\App_KernelDevDebugContainer([
    'container.build_hash' => 'Atg6xlf',
    'container.build_id' => 'ff99817a',
    'container.build_time' => 1704089829,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAtg6xlf');
