<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
     use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Blog' => [parent::class, 'Blog', null],
        "\0".parent::class."\0".'Liked' => [parent::class, 'Liked', null],
        "\0".parent::class."\0".'bannedUntill' => [parent::class, 'bannedUntill', null],
        "\0".parent::class."\0".'comments' => [parent::class, 'comments', null],
        "\0".parent::class."\0".'confirmationToken' => [parent::class, 'confirmationToken', null],
        "\0".parent::class."\0".'confirmed' => [parent::class, 'confirmed', null],
        "\0".parent::class."\0".'follow' => [parent::class, 'follow', null],
        "\0".parent::class."\0".'followers' => [parent::class, 'followers', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        "\0".parent::class."\0".'userProfile' => [parent::class, 'userProfile', null],
        "\0".parent::class."\0".'username' => [parent::class, 'username', null],
        'Blog' => [parent::class, 'Blog', null],
        'Liked' => [parent::class, 'Liked', null],
        'bannedUntill' => [parent::class, 'bannedUntill', null],
        'comments' => [parent::class, 'comments', null],
        'confirmationToken' => [parent::class, 'confirmationToken', null],
        'confirmed' => [parent::class, 'confirmed', null],
        'follow' => [parent::class, 'follow', null],
        'followers' => [parent::class, 'followers', null],
        'id' => [parent::class, 'id', null],
        'password' => [parent::class, 'password', null],
        'roles' => [parent::class, 'roles', null],
        'userProfile' => [parent::class, 'userProfile', null],
        'username' => [parent::class, 'username', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
